<?php

namespace GenAI\SqlMapper\Util;

/**
 * Stateless helper that compiles a mapper plan into PHP 5.3-safe source.
 *
 * Per #[Mapper] interface it emits a Cache\<Name> implementation whose methods
 * inline the prepared statement (no shared helpers, so a mapper method named
 * insert()/execute() can't recurse into a base), e.g.:
 *
 *   class UserMapper extends \GenAI\SqlMapper\AbstractMapper implements \App\UserMapper
 *   {
 *       public function findById($id)
 *       {
 *           $statement = $this->pdo->prepare('SELECT * FROM users WHERE id = :id');
 *           $statement->execute(array('id' => $id));
 *           $row = $statement->fetch();
 *           return $row === false ? null : $row;
 *       }
 *   }
 *
 * plus a Cache\Mappers registrar binding each interface in the container:
 *
 *   $container->register('App\\UserMapper', function (\GenAI\Container\Container $c) {
 *       return new \Cache\UserMapper($c->get('PDO'));
 *   });
 *
 * Compatible with PHP 5.3.29.
 */
class MapperDumper
{
    /**
     * Compile one mapper implementation class.
     *
     * @param string $cacheClass fully-qualified compiled class (e.g. "Cache\\ModuleA\\ProductMapper")
     * @param string $interface  fully-qualified mapper interface
     * @param array  $methods    method plans from the MapperProcessor
     * @param array  $hydrators  hydrator plans, keyed by generated method name
     * @return string PHP source
     */
    public static function dumpMapper($cacheClass, $interface, $methods, $hydrators = array())
    {
        // Split Cache\ModuleA_ProductMapper -> namespace "Cache", class "ModuleA_ProductMapper".
        $cacheClass = ltrim($cacheClass, '\\');
        $cut        = strrpos($cacheClass, '\\');
        $namespace  = substr($cacheClass, 0, $cut);
        $class      = substr($cacheClass, $cut + 1);

        $lines = array();
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace ' . $namespace . ';';
        $lines[] = '';
        $lines[] = '// Generated by GenAI\\SqlMapper\\Processor\\MapperProcessor - do not edit by hand.';
        $lines[] = '// new \\' . $cacheClass . '($pdo) implements \\' . ltrim($interface, '\\') . '.';
        $lines[] = '';
        $lines[] = 'class ' . $class
                 . ' extends \\GenAI\\SqlMapper\\AbstractMapper implements \\' . ltrim($interface, '\\');
        $lines[] = '{';
        foreach ($methods as $method) {
            $lines[] = self::dumpMethod($method);
        }
        foreach ($hydrators as $name => $hydrator) {
            $lines[] = self::dumpHydrator($name, $hydrator['class'], $hydrator['fields']);
        }
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Compile the Cache\Mappers registrar (loadInto, like Cache\Properties).
     *
     * @param array $mappers list of mapper records (interface + cacheClass)
     * @return string PHP source
     */
    public static function dumpRegistrar($mappers)
    {
        $lines = array();
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace Cache;';
        $lines[] = '';
        $lines[] = '// Generated by GenAI\\SqlMapper\\Processor\\MapperProcessor - do not edit by hand.';
        $lines[] = '// Cache\\Mappers::loadInto($container) registers each mapper, keyed by its interface.';
        $lines[] = '';
        $lines[] = 'class Mappers';
        $lines[] = '{';
        $lines[] = '    public static function loadInto(\\GenAI\\Container\\Container $container)';
        $lines[] = '    {';
        foreach ($mappers as $mapper) {
            $lines[] = self::dumpRegistration($mapper['cacheClass'], $mapper['interface']);
        }
        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * One inlined mapper method.
     *
     * @param array $method plan: name, kind, sql, params, placeholders
     * @return string
     */
    private static function dumpMethod($method)
    {
        $body = array();
        $body[] = '        $statement = $this->pdo->prepare(' . var_export($method['sql'], true) . ');';
        $body[] = '        $statement->execute(' . self::bindArray($method['placeholders']) . ');';

        $hydrator = isset($method['hydrator']) ? $method['hydrator'] : null;

        switch ($method['kind']) {
            case 'selectAll':
                if ($hydrator !== null) {
                    $body[] = '        $result = array();';
                    $body[] = '        foreach ($statement->fetchAll() as $row) {';
                    $body[] = '            $result[] = $this->' . $hydrator . '($row);';
                    $body[] = '        }';
                    $body[] = '        return $result;';
                } else {
                    $body[] = '        return $statement->fetchAll();';
                }
                break;
            case 'selectOne':
                $body[] = '        $row = $statement->fetch();';
                if ($hydrator !== null) {
                    $body[] = '        return $row === false ? null : $this->' . $hydrator . '($row);';
                } else {
                    $body[] = '        return $row === false ? null : $row;';
                }
                break;
            case 'insert':
                $body[] = '        return $this->pdo->lastInsertId();';
                break;
            default: // modify (update | delete)
                $body[] = '        return $statement->rowCount();';
                break;
        }

        return '    public function ' . $method['name'] . '(' . self::paramList($method['params']) . ')' . "\n"
             . '    {' . "\n"
             . implode("\n", $body) . "\n"
             . '    }' . "\n";
    }

    /**
     * One row->object hydrator (private). Each field is guarded with
     * array_key_exists so a SELECT of a subset of columns hydrates cleanly.
     *
     * @param string $name   generated method name (hydrate<ShortClass>)
     * @param string $class  fully-qualified result class
     * @param array  $fields field => ['kind' => 'setter'|'property', 'member' => ...]
     * @return string
     */
    private static function dumpHydrator($name, $class, $fields)
    {
        $body = array();
        $body[] = '        $object = new \\' . ltrim($class, '\\') . '();';
        foreach ($fields as $field => $target) {
            $cell = '$row[' . var_export($field, true) . ']';
            if ($target['kind'] === 'setter') {
                $assign = '$object->' . $target['member'] . '(' . $cell . ');';
            } else {
                $assign = '$object->' . $target['member'] . ' = ' . $cell . ';';
            }
            $body[] = '        if (array_key_exists(' . var_export($field, true) . ', $row)) {';
            $body[] = '            ' . $assign;
            $body[] = '        }';
        }
        $body[] = '        return $object;';

        return '    private function ' . $name . '($row)' . "\n"
             . '    {' . "\n"
             . implode("\n", $body) . "\n"
             . '    }' . "\n";
    }

    /**
     * Render the method signature parameters ($id, $name) from their names.
     *
     * @param string[] $params
     * @return string
     */
    private static function paramList($params)
    {
        $parts = array();
        foreach ($params as $name) {
            $parts[] = '$' . $name;
        }

        return implode(', ', $parts);
    }

    /**
     * Render the PDO bind array, array('id' => $id, ...), from placeholder names.
     *
     * @param string[] $placeholders
     * @return string
     */
    private static function bindArray($placeholders)
    {
        if (empty($placeholders)) {
            return 'array()';
        }

        $parts = array();
        foreach ($placeholders as $name) {
            $parts[] = var_export($name, true) . ' => $' . $name;
        }

        return 'array(' . implode(', ', $parts) . ')';
    }

    /**
     * One $container->register(...) line binding an interface to its compiled mapper.
     *
     * @param string $cacheClass fully-qualified compiled class
     * @param string $interface
     * @return string
     */
    private static function dumpRegistration($cacheClass, $interface)
    {
        return '        $container->register(' . var_export($interface, true)
             . ', function (\\GenAI\\Container\\Container $c) {' . "\n"
             . '            return new \\' . ltrim($cacheClass, '\\') . '($c->get(\'PDO\'));' . "\n"
             . '        });';
    }
}
